name: Say Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
